# Generated by Django 2.1.5 on 2019-01-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncall',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
