# Generated by Django 2.1.5 on 2019-01-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncall', '0003_auto_20190121_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
